### ISSUE TITLE
Req: Tag a new release

### ISSUE THREAD

**Issue by xiota** [aarnt/qt-sudo#2]
Please tag a new release, and don't forget to update:

https://github.com/aarnt/qt-sudo/blob/4eaad52ba5473141d5ac39f9be9636e1cdd393f4/sudo.cpp#L70

**Comment by yochananmarqos** [comment]
@aarnt Maybe that string is leftover from the `lxqt-sudo` port?

**Comment by aarnt** [comment]
@yochananmarqos  It's still used in qt-sudo with the "-v" param
