### ISSUE TITLE
C.UTF-8 message

### ISSUE THREAD

**Issue by wolfseifert** [aarnt/qt-sudo#3]
Running octopi using my de_DE.UTF-8 locale I get the message:

Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.

Patching qt-sudo with

<pre>
diff -upr a/sudo.cpp b/sudo.cpp
--- a/sudo.cpp	2024-05-23 17:53:04.967119754 +0200
+++ b/sudo.cpp	2024-05-23 17:54:35.334177682 +0200
@@ -336,7 +336,7 @@ void Sudo::child()
 
   *param_arg = nullptr;
 
-  setenv("LC_ALL", "C", 1);
+  setenv("LC_ALL", "C.UTF-8", 1);
 
   setsid(); //session leader
   execvp(params[0], const_cast<char **>(params.get()));
</pre>

solves the issue. There are more "C" locales in octopi itself (<kbd>octopihelper.cpp</kbd> and <kbd>unixcommand.cpp</kbd>), but this change in qt-sudo seems to fix it all.

**Comment by aarnt** [comment]
@wolfseifert  Thanks for the patch!
